### ISSUE TITLE
registering already registered accout sending me "problem with server" error

### ISSUE THREAD

**Issue by Arukenofu** [Rehart-Kcalb/EduNexus-Monolith#4]
![изображение](https://github.com/Rehart-Kcalb/EduNexus-Monolith/assets/126886598/6eaf14b9-761f-456d-9e0f-f1cbaf524510)

**Comment by Rehart-Kcalb** [comment]
I'd like to inform you that I've addressed this issue by implementing checks for Postgres error codes. This improvement should provide better error handling and troubleshooting capabilities within the code.
