### ISSUE TITLE
creating a course creates only fields with course name and description 

### ISSUE THREAD

**Issue by Arukenofu** [Rehart-Kcalb/EduNexus-Monolith#6]
![изображение](https://github.com/Rehart-Kcalb/EduNexus-Monolith/assets/126886598/386f77dd-998a-4ca3-ab47-3eb4d456ae93)

**Comment by Rehart-Kcalb** [comment]
Nothing wrong

**Comment by Arukenofu** [comment]
i edited my username and avatar, and yes, it's worked fine, but its still igni
![изображение](https://github.com/Rehart-Kcalb/EduNexus-Monolith/assets/126886598/a39c57d4-ba3d-4c6d-bacc-81ba607a7187)
